### ISSUE TITLE
Support for VirtualBox (OVF) box format

### ISSUE THREAD

**Issue by mnuthan1** [bacongravy/macinbox#18]
how can I generate OVF format for virtualbox using macinbox.

**Comment by bacongravy** [comment]
That's a great question! I am not a VirtualBox user, so I don't know the answer offhand.

Some quick googling suggests that it is possible to convert a vmx and vmdk (VMware machine definition and disk image) into an OVF/OVA, so one approach would be create the VMware vagrant box, and then try converting the embedded vmx/vmdk.

Alternatively, this project might be what you're looking for: https://github.com/geerlingguy/macos-virtualbox-vm

**Comment by bacongravy** [comment]
Here's another approach: https://github.com/AlexanderWillner/runMacOSinVirtualBox

I suspect one could add VirtualBox support to `macinbox` by following a similar pattern, along with the `VBoxManage convertfromraw` command for creating the VDI.

**Comment by bacongravy** [comment]
v3.1.0 has been released. After updating, you can use this feature like so:

```
macinbox --box-format virtualbox
```
