### ISSUE TITLE
Legal advice

### ISSUE THREAD

**Issue by robin850** [bacongravy/macinbox#19]
Hi,

First, kudos and thanks for sharing this project ! 🎉

I take the liberty to open this tiny ticket just to open a discussion around potential legal issues. IANAL but, searching for a technology similar to containers on macOS, someone on a topic stated that there may be legal issues to virtualization (the topic is [here](https://groups.google.com/forum/#!topic/darwin-dev/6-FP9GCsBG4) and is pretty interesting even though the legal notice wouldn't apply to for OS-level virtualization apparently).

Apparently, as [the macOS license](https://www.apple.com/legal/sla/docs/macOS1014.pdf) states, there are a few limitations that apply to virtualization (on page 2):

> B. Mac App Store License. If you obtained a license for the Apple Software from the Mac App Store or through an automatic download, then subject to the terms and conditions of this License and as permitted by the Services and Content Usage Rules set forth in the Apple Media Services Terms and Conditions (https://www.apple.com/legal/internet-services/itunes/) (“Usage Rules”), you are granted a limited, non-transferable, non-exclusive license
> * (i) ...
> * (ii) ...
> * (iii) to install, use and run up to two (2) additional copies or instances of the Apple Software within virtual operating system environments on each Mac Computer you own or control that is already running the Apple Software, for purposes of: (a) software development; (b) testing during software development; (c) using macOS Server; or (d) personal, non-commercial use.
>
> The grant set forth in Section 2B(iii) above does not permit you to use the virtualized copies or instances of the Apple Software in connection with service bureau, time-sharing, terminal sharing or other similar types of services.

Given that a lot of people ( 🙋‍♂️ ) don't read legal notices, it may be useful to add a tiny paragraph to the README file to warn people about that. AFAIK, there is no similar project to yours that does such mention but I don't know whether that's intentional or not. Maybe, something along these lines could be useful:

> Due to licensing limitations, you should not run more than two copies of macOS on the same Mac computer and limit their usage to software development, testing during software development, using macOS Server or personal/non-commercial use.
>
> Be sure to checkout [the software license agreements](https://www.apple.com/legal/sla/) that applies to your macOS version for more information.

What do you think ? Does that make sense ?

Have a nice day !

**Comment by bacongravy** [comment]
Hello, @robin850, and thank you for your interest!

The [VMware Fusion documentation](https://docs.vmware.com/en/VMware-Fusion/11/com.vmware.fusion.using.doc/GUID-474FC78E-4E77-42B7-A1C6-12C2F378C5B9.html) provides this information about using macOS as a guest:

> Mac OS X, OS X, or macOS virtual machines that you create in Fusion can run on any Apple-branded hardware that uses Intel processors. The Apple licensing agreement defines the situations when it is permissible to virtualize Mac OS X, OS X, or macOS. Fusion does not change these terms or enable macOS on non-Apple hardware. You cannot use a Mac OS X, OS X, or macOS virtual machine in another VMware product, such as Workstation Pro.

The [VirtualBox documentation](https://www.virtualbox.org/manual/ch03.html#intro-macosxguests) provides this information about using macOS as a guest:

> Mac OS X is commercial, licensed software and contains both license and technical restrictions that limit its use to certain hardware and usage scenarios. You must understand and comply with these restrictions.

I wasn't able to find any statements along those lines in the [Parallels documentation](https://kb.parallels.com/en/124223) for guest OS support.

I do think it would be reasonable to remind people to review their OS software license agreement if they have questions about the permissibility of macOS virtualization. I do not think it would be appropriate for me to provide legal advice regarding how people should interpret that license.

Perhaps something like this in the README:

> **Note:** This software does not virtualize macOS; it assists you in preparing the OS to be virtualized by other software. If you have questions about the permissibility of virtualizing macOS you may want to review the documentation for the virtualization software you are using and the [software license agreement](https://www.apple.com/legal/sla/) that applies to your version of macOS. 



Would that address your concerns?

**Comment by robin850** [comment]
> I do not think it would be appropriate for me to provide legal advice regarding how people should interpret that license.

Yes, totally fair point, you're right !

Your note looks great ! 👍 Actually, I didn't think about looking at VirtualBox or VMware documentation at all ; now that I read your message, that seems obvious but given how simple the note is, that still makes sense to put it in the README IMO.

**Comment by bacongravy** [comment]
This showed up in https://github.com/bacongravy/macinbox/commit/1b3458463ca58e8f0c4161d8b88847455694c1d7. It will go out with the v3.2.0 release.

**Comment by bacongravy** [comment]
v3.2.0 has been released to rubygems.org. Closing.
