### ISSUE TITLE
Small issue with --user-script

### ISSUE THREAD

**Issue by egandro** [bacongravy/macinbox#29]
The user script will run before the 

"Setting the KextPolicy to allow loading the VMware kernel extensions..."

So I can't set my own stuff to 

{@image_mountpoint}/private/var/db/SystemPolicyConfiguration/KextPolicy

Since this will be always  overwritten.

Can you please add a "Skipting KextPolicy because file already exists"?

**Comment by bacongravy** [comment]
Oh!  That’s unfortunate. I’m sorry I didn’t take that into account.

I can definitely split the KextPolicy code up into one piece that creates the file, if necessary, and another that inserts the values.

I will also consider moving the user script execution to happen after the customizations for VMware get laid down.

**Comment by egandro** [comment]
I suggest splitting you code in parts:

1) Create the SQL File if it does not exist but without inserts

2)Always to this Insert / Replaces Statements

```
BEGIN TRANSACTION;
INSERT OR REPLACE INTO kext_policy VALUES('EG7KH642X6','com.vmware.kext.VMwareGfx',1,'VMware, Inc.',1);
INSERT OR REPLACE INTO kext_policy VALUES('EG7KH642X6','com.vmware.kext.vmmemctl',1,'VMware, Inc.',1);
INSERT OR REPLACE INTO kext_policy VALUES('EG7KH642X6','com.vmware.kext.vmhgfs',1,'VMware, Inc.',1);
COMMIT;
```

**Comment by bacongravy** [comment]
I've implemented that here:

https://github.com/bacongravy/macinbox/compare/bcc8f9fbbe6ab6cb478bf44905779d16db4e5859..bff9b52a1df5e5d5c17e51c4de6c4e6e002ecbe0

Please let me know if that resolves the issue for you.

**Comment by egandro** [comment]
Thanks a lot!

I will test this today.

**Comment by egandro** [comment]
Btw. can you please check for the return code of the script?

If the result is != 0 fail stop the execution of macinbox.

**Comment by egandro** [comment]
We can no debug user scripts :)

Check my pull request.

**Comment by bacongravy** [comment]
Thanks!  I’m away from my computer this weekend but I’ll see about getting your sample scripts merged in after that.

It should already be the case that when a user-script exits non-zero it fails the process, are you seeing different behavior?

**Comment by bacongravy** [comment]
Tagged and released: https://github.com/bacongravy/macinbox/tree/v3.3.0
