### ISSUE TITLE
Idea for Kickstart fix

### ISSUE THREAD

**Issue by egandro** [bacongravy/macinbox#30]
This worked until 10.14

```sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -off -restart -agent -privs -all -allowAccessFor -allUsers```

Apple broke it:

`Warning: macos 10.14 and later only allows control if Screen Sharing is enabled through System Preferences.`

Any idea how to fix this with one of our pre-scripts?

**Comment by egandro** [comment]
Ok I found it: https://support.apple.com/en-en/HT209161

But I have no idea how to translate this into a start script.

**Comment by bacongravy** [comment]
Do you need ARD in particular or just VNC in general?

**Comment by egandro** [comment]
Both would be cool.

I would prefere the Config as Json file, since this has 10+ buttons.

**Comment by egandro** [comment]
Maybe
Maybe 2 short cuts

- --enable-vnc (do the most compatible thing with the same vagrant passwort)
- --vnc-rw-password (specify a rw password)
- --ard-config-file
- --vnc-config-file ? duno if this is neccesarray

**Comment by bacongravy** [comment]
You could try adding this to your user script:

```bash
/usr/libexec/PlistBuddy -c 'Add :com.apple.screensharing bool False' "${CHROOT}/private/var/db/com.apple.xpc.launchd/disabled.plist"
```

If you confirm that that still works in Mojave I could add an `--enable-screen-sharing` option that did that for you.

**Comment by egandro** [comment]
I'll try this :) I love scripted VMs :)))

**Comment by egandro** [comment]
I can confirm this works.

**Comment by egandro** [comment]
Well - there is a problem :(

I have no idea how to fix this. I fooled around for a view days.

'Add :com.apple.screensharing bool False'

This will enable the screen sharing. However I can only connect via closed source VNC tools, since no open source tool offers the apple authentication protocols.

I like to do some extra provisioning using vncdotool (https://github.com/sibson/vncdotool) - but this does not support the Apple protocols.

However using the --legacy option or a screen sharing password - that's no problem.

Do you know a user script way to do this?

**Comment by bacongravy** [comment]
You could try running your own VNC server, for example https://github.com/TigerVNC/tigervnc.

I suspect that you’re going to have an easier time if you do this kind of setup in a vagrant provisioning step, after the box boots for the first time, rather than in a macinbox user script.

Or, you could  try taking advantage of the VNC sever built into VMware/esxi: https://www.virtuallyghetto.com/2012/01/using-vnc-client-to-connect-to-vms-in.html

If you’re using VMware Fusion it’s even easier: I think you can enable the hypervisor VNC in the advanced settings UI for the VM.

**Comment by egandro** [comment]
Well :( I have a solution.

This is so sick.

I connect to VMWare Fusion VNC - and run a Vncdotool in a Shell script & OCR via https://github.com/tesseract-ocr/tesseract 

Apple decided to go with random Y values. The X are always the same...

After two days a macinbox Mac can create a macinbox mac...

"Security" the Apple way :(

Why didn't they chose to implement their own remote framebuffer protocol as Microsoft did? 

VNC was unsecure at the first place. They notice the flaws after 10+ years - and now they do obfuscation - not fixing.

Thread can be closed?

**Comment by bacongravy** [comment]
Wow, that sounds like a hassle!  I'm glad you were able to find a solution.

I will close this issue now, but if someone else wants to make the case for needing a `--enable-screen-sharing`, I'm open to hearing it!
