### ISSUE TITLE
Feature request: find out how to csrutil disable

### ISSUE THREAD

**Issue by egandro** [bacongravy/macinbox#32]
--csr-disable would be so awesome

I only found this: https://www.imore.com/how-turn-system-integrity-protection-macos

But maybe there is a OSX'ish chroot?

**Comment by egandro** [comment]
There is a jail equivalent:

http://galvanist.com/post/56925855686/chroot-jails-on-os-x

**Comment by egandro** [comment]
Yes there is BSD chroot. So we might have a chance.

**Comment by bacongravy** [comment]
Duplicate of #4.
