### ISSUE TITLE
vagrant group missing from box

### ISSUE THREAD

**Issue by mmannerm** [bacongravy/macinbox#37]
The `vagrant` user group is missing from the vagrant box, which makes using e.g. `rsync` synced folders require some work before you can make them work, as vagrant assumes both the user and user group are present in the box.

```
Error: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

find /vagrant '!' -type l -a '(' ! -user vagrant -or ! -group vagrant ')' -exec chown vagrant:vagrant '{}' +

Stdout from the command:



Stderr from the command:

find: -group: vagrant: no such group
---- End output of vagrant up --provider virtualbox ----
```

**Comment by mmannerm** [comment]
A workaround now is to add `rsync__chown: false` to the `c.vm.synced_folder` parameters, but it will not make the synced files to be owned by vagrant user.

**Comment by bacongravy** [comment]
@mmannerm Thanks for reporting this issue. I’ve always wondered why other tools for creating vagrant boxes also created the `vagrant` group in addition to the user.

There is already a script installed by `macinbox` on the box that runs on first boot and waits for the `vagrant` user to be created, so I believe it should be possible to update that script to create the group and put the user in it, before `ssh` access is enabled.  I’ll look into it.

**Comment by bacongravy** [comment]
I've fixed this with https://github.com/bacongravy/macinbox/commit/b21dc786bfadd37f6988e22920c1d797f2a780a8. It will be in the upcoming v3.4.0 release.

**Comment by bacongravy** [comment]
v3.4.0 has been released. Closing.
