### ISSUE TITLE
macinbox stuck on Creating dynamic image

### ISSUE THREAD

**Issue by tschoonj** [bacongravy/macinbox#41]
Trying to create a High Sierra image with the following command, leads to `macinbox` getting stuck at Creating dynamic image (already 15 hours...):

```shell
$ sudo macinbox --box-format virtualbox --name high-sierra-gui -m 8192 --installer /Applications/Install\ macOS\ High\ Sierra.app --no-fullscreen
• Checking macOS versions...
  + Warning: host OS version (10.14.5) and installer OS version (10.13.6) do not match
• Creating image from installer...
  + Creating and attaching wrapper disk image...
  + Creating and attaching a new blank disk image...
  + Installing macOS...
    - installer: 100% done 
  + Configuring the primary user account...
  + Installing the default insecure vagrant ssh key...
  + Enabling password-less sudo...
  + Enabling sshd...
  + Enabling HiDPI resolutions...
  + Saving the image...
• Creating VDI from image...
  + Copying the image...
  + Attaching the image...
  + Setting up EFI partition...
  + Converting the image to VDI format...
Converting from raw image file="/dev/disk4" to file="/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/create_vdi_from_image.4nHB0nLT/macinbox.vdi"...
Creating dynamic image with size 68719476736 bytes (65536MB)...

```

Any thoughts?

**Comment by bacongravy** [comment]
Hello, @tschoonj !  Thank you for this report.  I have not seen this hang myself.  The conversion usually only takes minutes, not hours.

A few questions... does this reproduce if you try again with the `--verbose` flag?    And what versions of `macinbox` and VirtualBox are you using? Thanks!

**Comment by tschoonj** [comment]
Hi @bacongravy,

I have to correct my earlier post: it's not actually stuck, it's just that writing the vdi file is extremely slow (like < 1 MB/s).

I am using the latest version of `macinbox` and VirtualBox (6.0.8).

**Comment by tschoonj** [comment]
This eventually worked, but had to wait a couple of days before the image had been converted.

Thanks!
