### ISSUE TITLE
VMWare Fusion 11.5 ignores HiDPI setting in VMX file

### ISSUE THREAD

**Issue by bacongravy** [bacongravy/macinbox#44]
With VMWare Fusion 11.5 the `gui.fitguestusingnativedisplayresolution` setting in VMX files is getting ignored.  It appears that v11.5 is case-sensitive for this setting, whereas previous versions of Fusion were case-insensitive.

With Fusion 11.5, the setting must be capitalized like this to have an effect:

    gui.fitGuestUsingNativeDisplayResolution = "TRUE"

Unfortunately, `vagrant`'s long-standing behavior is to downcase this setting in the VMX every time you run `vagrant up`.

If you power off the VM using Fusion, change the setting with Fusion, and then power it back on with Fusion, the setting is preserved, and the VM runs with HiDPI enabled. But as soon as you run `vagrant up` again the setting gets downcased and HiDPI stops working.

**Comment by bacongravy** [comment]
This was working fine with VMWare Fusion 11.1.0. I don't think this is something I can address in `macinbox`. Does somebody have a support contract with VMWare that they want to use to report this regression?

**Comment by yeahdongcn** [comment]
I have reported this internally and the team is looking into this right now.

**Comment by yeahdongcn** [comment]
This issue is resolved in the newly released VMware Fusion 11.5.1. Please verify and close it. Thanks.

**Comment by bacongravy** [comment]
Verified with VMware Fusion 11.5.1 on Catalina. Fixed! Thank you @yeahdongcn for the quick turnaround!
