### ISSUE TITLE
Box created with Parallels Desktop 15.1.2 fails to boot

### ISSUE THREAD

**Issue by bacongravy** [bacongravy/macinbox#49]
As discovered while investigating #47, if I use Parallels Desktop 15.1.2 to create a box, then the created box fails to boot. When Parallels Desktop 15.0.0 is used to generate the box then it works fine.  The 15.0.0-created box boots fine with 15.1.2, so I suspect that the problem is that the 15.1.2 version of prl_convert tool is behaving differently and producing an unbootable hdd.

**Comment by schrodincat** [comment]
The issue seems to be fixed in Parallels Desktop 15.1.3. I’ve successfully created and launched a box with it.

**Comment by bacongravy** [comment]
@schrodincat Thank you for the update! I just confirmed as well, Parallels Desktop 15.1.3 (47255) and macOS Catalina 10.15.3 (19D76) work together to produce a bootable 10.15.3 box.
