### ISSUE TITLE
Catalina 10.15.4 issue - machine fails to boot with startup error

### ISSUE THREAD

**Issue by nycnewman** [bacongravy/macinbox#52]
Error message below. WHat other information might you need to debug this?

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'macinbox'...
==> default: Generating MAC address for NAT networking...
==> default: Setting the name of the VM: 2-vagrant-files_default_1586646461190_52216
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'paused' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue.

**Comment by nycnewman** [comment]
Turns out issue was related to VIrtualBox. 6.1.4 on MacOS 10.15.4 cannot start correctly when 32Gb or greater, or 6 virtual cores or greater allocated to instance.

**Comment by bacongravy** [comment]
@nycnewman I’m glad you got it figured it out. Thank you for following up in the issue with your findings.
