### ISSUE TITLE
Allow to specify VRAM amount

### ISSUE THREAD

**Issue by andreiborisov** [bacongravy/macinbox#57]
In addition to CPU and memory, it would be useful to be able to specify the amount of VRAM, since the default value (at least for Parallels) is quite low.

It should be fairly straightforward to implement, again, for Parallels it would be:

```
prl.customize ["set", :id, "--videosize", "256"]
```

This would set VRAM to 256 MB.

**Comment by bacongravy** [comment]
Hi @schrodincat, thanks for the feature request.  Is it important to you that this setting be configurable? I’m wondering if it might be better to just set it to 256 for all boxes.

**Comment by andreiborisov** [comment]
Yeah, I think setting it to 256 for all boxes is fine.

However, wouldn’t the appropriate amount be different for different providers (256 is maximum for Parallels currently since they don’t support hardware 3D acceleration)? In that case, it probably would be easier to allow customization (unless you want to set VRAM only for Parallels provider, which is also fine by me🙂).

The only real problem with the fixed amount I can foresee is that it'll probably need to be changed in the future due to macOS requirement changes and whatnot.
