### ISSUE TITLE
Any way to get sound working in VirtualBox VM?

### ISSUE THREAD

**Issue by JonHolman** [bacongravy/macinbox#60]
I've been playing around with it, but I cannot seem to find a way to get sound working from within the virtualbox VM.  Everything else seems to be working no problem.  Does sound work with VMware?

**Comment by bacongravy** [comment]
@JonHolman I haven’t tested it recently, but yes, it is my recollection that VMware and Parallels both support sound output from the guest macOS VM.

I believe both VMware and Parallels offer free trials, I encourage you to try them out to verify for yourself to see if paying for them is worth it (I think it is!).  In my experience they work much better than VirtualBox.

**Comment by JonHolman** [comment]
Thanks @bacongravy I’ll give it a try
